// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXtSV3seuvG8_0rFwRbSBgFimzevqwNw',
    appId: '1:575169852378:web:e6aab337a53ad28683c6e3',
    messagingSenderId: '575169852378',
    projectId: 'senefavores',
    authDomain: 'senefavores.firebaseapp.com',
    storageBucket: 'senefavores.firebasestorage.app',
    measurementId: 'G-E17X0S72ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69EOgV2U4DaTfsd4kyZ1Fdh08in7XpWw',
    appId: '1:575169852378:android:6e1c8719cc51b98083c6e3',
    messagingSenderId: '575169852378',
    projectId: 'senefavores',
    storageBucket: 'senefavores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1w6dtkDWHMZOzBbMIAnzozGsLaKwKL78',
    appId: '1:575169852378:ios:d5d8cc623426ed5083c6e3',
    messagingSenderId: '575169852378',
    projectId: 'senefavores',
    storageBucket: 'senefavores.firebasestorage.app',
    iosBundleId: 'com.examples.senefavores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1w6dtkDWHMZOzBbMIAnzozGsLaKwKL78',
    appId: '1:575169852378:ios:8450c0db3046e50883c6e3',
    messagingSenderId: '575169852378',
    projectId: 'senefavores',
    storageBucket: 'senefavores.firebasestorage.app',
    iosBundleId: 'com.example.senefavores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQXtSV3seuvG8_0rFwRbSBgFimzevqwNw',
    appId: '1:575169852378:web:853956b425b444f683c6e3',
    messagingSenderId: '575169852378',
    projectId: 'senefavores',
    authDomain: 'senefavores.firebaseapp.com',
    storageBucket: 'senefavores.firebasestorage.app',
    measurementId: 'G-VMSQHJN799',
  );
}
